---
title: "HW4"
author: "Tommy Cheng"
date: "October 8, 2016"
output: html_document
---


## Homework4
Problem1a: (1,2,3,...,19,20)
```{r}
a <- (1:20)
```

Problem1b: (20,19,...,2,1)
```{r}
b <- (20:1)
```

Problem1c: (1,2,3,...,19,20,19,18,...,2,1)	
```{r}
c(1:20,19:1)
```

Problem1d: (4,	6,	3)	and	assign	it	to	the	name	tmp.	
```{r}
tmp <- c(4, 6, 3)
```
Problem1e) (4,6,3, 4,6,3,...,4,6,3) where there are 10 occurrences of 4.
```{r}
rep(tmp,10)
```
Problem1f)
```{r}
c( rep(tmp,10), 4)
```
Problem1g)
```{r}
c(rep(4,10), rep(6,20), rep(3,30))
```
Problem2)
```{r}
tmp <- seq(3,6,by=0.1)
exp(tmp)*cos(tmp)
```
Problem3a)
```{r}
x<-seq(3,36,3)
y<-seq(1,34,3)
v <- (0.1^x*0.2^y)
```
Problem3b)
```{r}
(2^c(1:25))/c(1:25)
```
Problem4a)
```{r}
tmp <- c(10:100)
sum(tmp^3+4*tmp^2)
```
Problem4b)
```{r}
tmp <-c(1:25)
sum((2^tmp)/tmp + 3^tmp/(tmp^2))
```
Problem5a)
```{r}
s1 <- rep('Label', 30)
s2 <- c(1:30)
paste(s1, s2, sep=" ")
```
Problem5b)
```{r}
s3 <- rep('fn', 30)
s4 <- c(1:30)
paste(s3, s4, sep="")
```
Problem6 create xVec and yVec
```{r}
set.seed(50)
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
```
Problem6a)
```{r}
yVec[-1]-xVec[-250]
```
Problem6b)
```{r}
sin(yVec[-250]) / cos(xVec[-1])
```
Problem6c)
```{r}
xVec[-c(249,250)] + 2*xVec[-c(1,250)]-xVec[-c(1,2)]
```
Problem6d)
```{r}
sum(exp(-xVec[-1])/(xVec[-250]+10))
```
Problem7a)
```{r}
yVec[yVec>600]
```
Problem7b)
```{r}
which(yVec>600)
```
Problem7c)
```{r}
xVec[yVec>600]
```
Problem7d)
```{r}
(abs(xVec-mean(xVec)))^(1/2)
```
Problem7e)
```{r}
length(which(yVec >= max(yVec)-200))
```
Problem7f)
```{r}
length(which(yVec >= max(yVec)-200))
```
Problem7g)
```{r}
xVec[order(yVec)]
```
Problem7h)
```{r}
yVec[seq(1,248,3)]
```
Problem8)
```{r}
1+sum(cumprod(seq(2,38,2)/seq(3,39,2)))
```

